-- Role
insert into roles (uuid, name, created_at, updated_at) values
  (REPLACE(UUID(), '-', ''), 'ROLE_ADMIN', now(), now()),
  (REPLACE(UUID(), '-', ''), 'ROLE_USER', now(), now());

-- Permission
insert into permissions (uuid, name, description, created_at, updated_at) values
  (REPLACE(UUID(), '-', ''), 'HOME_VIEW', 'View the Home page', now(), now()),
  (REPLACE(UUID(), '-', ''), 'PERMISSION_READ', 'View the permissions data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'PERMISSION_WRITE', 'Write the permissions data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'PERMISSION_DELETE', 'Delete the permissions data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'ROLE_READ', 'View the roles data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'ROLE_WRITE', 'Write the roles data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'ROLE_DELETE', 'Delete the roles data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'ROLE_PERMISSIONS_READ', 'View the role permissions data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'ROLE_PERMISSIONS_WRITE', 'Write the role permissions data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'ROLE_PERMISSIONS_DELETE', 'Delete the role permissions data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'USER_READ', 'View the users data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'USER_WRITE', 'Write the users data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'USER_DELETE', 'Delete the roles data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'EMPLOYEE_READ', 'View the employees data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'EMPLOYEE_WRITE', 'Write the employees data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'EMPLOYEE_DELETE', 'Delete the employees data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'CUSTOMER_READ', 'View the customers data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'CUSTOMER_WRITE', 'Write the customers data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'CUSTOMER_DELETE', 'Delete the customers data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'CUSTOMER_CARS_READ', 'View the customer cars data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'CUSTOMER_CARS_WRITE', 'Write the customer cars data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'CUSTOMER_CARS_DELETE', 'Delete the customer cars data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'SERVICE_READ', 'View the services data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'SERVICE_WRITE', 'Write the services data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'SERVICE_DELETE', 'Delete the services data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'SUPPLIER_READ', 'View the suppliers data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'SUPPLIER_WRITE', 'Write the suppliers data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'SUPPLIER_DELETE', 'Delete the suppliers data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'CAR_PARTS_READ', 'View the car parts data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'CAR_PARTS_WRITE', 'Write the car parts data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'CAR_PARTS_DELETE', 'Delete the car parts data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'SERVICE_ORDERS_READ', 'View the service orders data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'SERVICE_ORDERS_WRITE', 'Write the service orders data', now(), now()),
  (REPLACE(UUID(), '-', ''), 'SERVICE_ORDERS_DELETE', 'Delete the service orders data', now(), now());

-- Role-Permission mapping
insert into role_permissions (role_id, permission_id) values
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'HOME_VIEW')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'PERMISSION_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'PERMISSION_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'PERMISSION_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'ROLE_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'ROLE_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'ROLE_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'ROLE_PERMISSIONS_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'ROLE_PERMISSIONS_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'ROLE_PERMISSIONS_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'USER_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'USER_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'USER_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'EMPLOYEE_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'EMPLOYEE_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'EMPLOYEE_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'CUSTOMER_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'CUSTOMER_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'CUSTOMER_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'CUSTOMER_CARS_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'CUSTOMER_CARS_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'CUSTOMER_CARS_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'SERVICE_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'SERVICE_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'SERVICE_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'SUPPLIER_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'SUPPLIER_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'SUPPLIER_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'CAR_PARTS_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'CAR_PARTS_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'CAR_PARTS_DELETE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'SERVICE_ORDERS_READ')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'SERVICE_ORDERS_WRITE')),
  ((select id from roles where name = 'ROLE_ADMIN'), (select id from permissions where name = 'SERVICE_ORDERS_DELETE'));
